// Automatically generated by Latte makefile
extern const char latte_pkgdatadir[] = "/usr/local/share/latte";
extern const char latte_version[] = "2.1";
extern const char latte_url[] = "http://www.latte.org/";
